### ISSUE TITLE
Can you provide the colors only in plain text?

### ISSUE THREAD

**Issue by AmmarCodes** [zaynali53/Zeus-Theme#2]
Hello,

I liked the colorscheme, I'd like to use them in my Xresources.
Can you provide the color palette? I tried to extract them from the repo but didn't recognize them well.

Thanks!

**Comment by zaynali53** [comment]
My pleasure @AAlakkad.

You can find all the colors from that <b><a target='_blank' href='http://eclipsecolorthemes.org/?view=theme&id=35350'>link</a></b>

**Comment by AmmarCodes** [comment]
That's all I needed, thanks!
