### ISSUE TITLE
Line Select / Highlight Color

### ISSUE THREAD

**Issue by robertbenjamin** [zaynali53/Zeus-Theme#3]
The line select color seems to be too dark, is it intended to look like this?

![Zeus Highlight](http://i.imgur.com/mEJ5IYI.png)

![Spacegrey Highlight](http://i.imgur.com/p3meWMY.png)

Thanks for the theme, I really love it (it's replacing Spacegrey for me, I needed something fresh).

**Comment by zaynali53** [comment]
Yes @robertbenjamin 
However i'll also make a lighter look :) Thanks for the feedback. Happy Coding!

**Comment by robertbenjamin** [comment]
Awesome, look forward to it! :+1:

**Comment by zaynali53** [comment]
@robertbenjamin 
Theme Updated, also added Darker look. You can try it now :)

**Comment by robertbenjamin** [comment]
<3
