### ISSUE TITLE
For another app

### ISSUE THREAD

**Issue by Alexey-T** [zaynali53/Zeus-Theme#4]
Hi;
good theme.
Cudatext has support for themes too [uvviewsoft.com; last beta]
Maybe you can port it?

**Comment by zaynali53** [comment]
Thanks and I've ported it.

[Zeus CudaText](https://github.com/zaynali53/Zeus-Theme/blob/master/CudaText/Zeus-CudaText.json)

**Comment by Alexey-T** [comment]
Tks for this work. I noted--tree selitem color/font not Okey 

![tree](https://cloud.githubusercontent.com/assets/4154978/13887578/e0aa3736-ed55-11e5-96df-598502841438.png)

**Comment by zaynali53** [comment]
Thanks. Fixed. https://github.com/zaynali53/Zeus-Theme/commit/c7f5994eae0bc26c34f62b2bf9ac04fc1e8ed97c

![capture](https://cloud.githubusercontent.com/assets/8646770/13888531/aa21e930-ed63-11e5-881a-464b7a8f6e0c.PNG)

**Comment by Alexey-T** [comment]
Find-dlg. maybe agressive lite buttons. and dropdown "v" arrow 
![btn](https://cloud.githubusercontent.com/assets/4154978/13888660/fcdaee68-ed5b-11e5-8a12-eb9129d01d96.png)

**Comment by Alexey-T** [comment]
Command[F1] dialog agressive?
or it's like ST3?

![cmd](https://cloud.githubusercontent.com/assets/4154978/13888764/a46505a6-ed5c-11e5-8112-1d418d4ee3e0.png)

**Comment by Alexey-T** [comment]
gutter: ST3 has dark BG for caret-line. 
here: not dark
![gutt](https://cloud.githubusercontent.com/assets/4154978/13889975/ac406576-ed62-11e5-934e-7782cf94c33f.png)

**Comment by zaynali53** [comment]
Here: https://github.com/zaynali53/Zeus-Theme/commit/bac648d76af7e2c6e00f5a31c12864f81a18a167

![capture](https://cloud.githubusercontent.com/assets/8646770/13891094/f08b60d8-ed70-11e5-9573-7a4bbb7d9898.PNG)

**Comment by Alexey-T** [comment]
Good- looks darker

**Comment by Alexey-T** [comment]
This Img is good for preview for Cuda

**Comment by zaynali53** [comment]
Awesome!

**Comment by Alexey-T** [comment]
will be in AddonMangr https://sourceforge.net/projects/cudatext/files/addons/themes/

**Comment by zaynali53** [comment]
This image is added as the CudaText Preview. 

![cudatext](https://cloud.githubusercontent.com/assets/8646770/13891943/0cc8a18e-ed76-11e5-9f5a-afc2fd733fea.PNG)

**Comment by Alexey-T** [comment]
(beta)Added one item "editor, combobox border" for 1-line edits
- Icons [+] bg-color: why lite gray?

**Comment by zaynali53** [comment]
How about this?

![capture](https://cloud.githubusercontent.com/assets/8646770/13904958/a02b4946-eed3-11e5-8932-11b3cc052ed8.PNG)

**Comment by Alexey-T** [comment]
This better. More dark. (don't forget new color "combobox border")

**Comment by zaynali53** [comment]
Yes. 

![capture](https://cloud.githubusercontent.com/assets/8646770/13905111/e42a429c-eed7-11e5-8a5d-dbcb37449fe3.PNG)

**Comment by Alexey-T** [comment]
red hilite of button? hm. Weird

**Comment by zaynali53** [comment]
This is the active state not hover

**Comment by Alexey-T** [comment]
Okey

**Comment by zaynali53** [comment]
And you added theme as a plugin. can you add this theme as a default dark theme in the editor as there are only two light one?

**Comment by zaynali53** [comment]
Fix Commit https://github.com/zaynali53/Zeus-Theme/commit/516feac1dcb9181aed0f5f63940fd00236bd49a1

**Comment by Alexey-T** [comment]
theme is not color rich (40 styles not differ), and I try to have Zip

**Comment by zaynali53** [comment]
Okay

**Comment by zaynali53** [comment]
Color rich? i didn't understand?

**Comment by Alexey-T** [comment]
I asked 3-4 more ST3 authors. no reply. E.g. Material theme is super popular. (maybe you want to port Material)

**Comment by Alexey-T** [comment]
'not color rich' -no 40 different colors in 40 styles. only 8-15 diff colors.

**Comment by zaynali53** [comment]
Hmm got it.
