### ISSUE TITLE
Update for PHP- and Webstorm 2016?

### ISSUE THREAD

**Issue by matthijs110** [zaynali53/Zeus-Theme#8]
The newer versions require a `.icls` file. When I import the xml file, the font is way to big and colors are not as they should be.

**Comment by zaynali53** [comment]
@matthijs110 i couldn't reproduce it. I installed the latest PHPStorm and activated zeus by importing it in my `username > .PhpStorm2016.1 > config > colors` directory. Here is the result

![capture](https://cloud.githubusercontent.com/assets/8646770/16266237/3b1c0770-389d-11e6-9862-65638ad0ab9f.PNG)

And `.icls` extension doesn't matter as PHPStorm will create it after reading the `.xml` file. However, i'll change the extension too.

Overall, can you show me a screenshot so i can fix the colors and see the problem visually?

**Comment by matthijs110** [comment]
It looks like this:

![](http://puu.sh/pBOpx/99d15ffb73.png)

I would like to have it just as nice as in Sublime Text:

![](http://puu.sh/pBOvH/e695671414.png)

**Comment by zaynali53** [comment]
@matthijs110 ok. Are you using zeus (phpstorm-themes.com) or from github?

**Comment by matthijs110** [comment]
phpstorm-themes.com

**Comment by zaynali53** [comment]
@matthijs110 i got it :) phpstorm-themes.com doesn't updates the zeus and there's no option for me to update my theme as i commit more changes into it so it's using the initial version of zeus. That's what causing you problems in syntax highlight.

**Comment by zaynali53** [comment]
I've updated the color scheme to `icls` and now you can try it out. clone the repository or download it and then import that phpstorm zeus into your colors directory.

**Comment by matthijs110** [comment]
It is a lot nicer now :) I did change the font family, size and spacing a bit, but it looks nice now :)

![](http://puu.sh/pC367/891130e825.png)

Thanks for your help! 👍
